AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31 
Description: >- 
  SAM Template for the Event-Driven Image-Processing Pipeline
  This Pipeline validates images, generates thumbnails, extracts metadata,
  store results in DynamoDB, and also includes an API Endpoint for processing status

Resources:
  UploadsBucket:
    Type: AWS::S3::Bucket  #This tells CloudFormation to create s3 Bucket. 
    Properties:
      BucketName: image-uploads-bucket-us-east-1-2025
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true 
        BlockPublicPolicy: true 
        IgnorePublicAcls: true
        RestrictPublicBuckets: true 

  ThumbNailsBucket:
    Type: AWS::S3::Bucket 
    Properties:
      BucketName: thumbnails-bucket-us-east-1-2025
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true 
        BlockPublicPolicy: true 
        IgnorePublicAcls: true
        RestrictPublicBuckets: true 